### PR TITLE
a-comp tweaks

### PR DESCRIPTION
**Pull request by johannes-mueller**
This aims to follow-up the discussion of [PR #370](https://github.com/Ardour/ardour/pull/370) in ardour/ardour. 

Some of the points implemented here were already discussed over there. As soon as the short term development of a-comp and maybe a-expander stabilizes, a PR will be submitted for merge in ardour/ardour

### CODE REVIEW

**Comment by lucianodato** [comment]
Regarding your nice gui additions, your gain reduction meter is much nicer and intuitive than the native one. Is it adding adding a label and removing the native one too much work? How do you feel about that?

**Comment by johannes-mueller** [comment]
The native meters appear automatically in the generic gui depending on what control output ports the plugin defines. So dropping the native one only works by dropping the control port which would impose a limitation for the plugin hosts.

Adding a label to the graph is something that I will probably do one day.

**Comment by zamaudio** [comment]
Is this fully merged in Ardour yet?  Any reason not to?

**Comment by johannes-mueller** [comment]
Closed because rebased version filed against origin/master

**Pull request closed without merging**
